worker_processes auto;
rtmp_auto_push on;
events {}
rtmp {
    server {
        listen 1935;
        listen [::]:1935 ipv6only=on;

        application live {
            live on;
            record off;

            # HTTP callbacks to NestJS for OBS logic and analytics
            on_publish http://app:5550/api/v1/churches/callbacks/rtmp/publish;
            on_publish_done http://app:5550/api/v1/churches/callbacks/rtmp/done;
        }
    }
}
